export const employees = [
  {
    id: 0,
    name: "Adrien Hobbs",
    title: "Developer",
    email: "adrien.hobbs@weareglow.com",
    phone: "518.488.4375",
  },
  {
    id: 1,
    name: "Alan Pierson",
    title: "Senior Integrated Producer",
    email: "alan.pierson@weareglow.com",
    phone: "615.347.5238",
  },
  {
    id: 2,
    name: "Alex Chang",
    title: "Client Operations & Project Manager",
    email: "alex.chang@weareglow.com",
    phone: "925.431.9311",
  },
  {
    id: 3,
    name: "Alex Husband",
    title: "Associate Creative Director",
    email: "alex.husband@weareglow.com",
    phone: "856.979.5451",
  },
  {
    id: 4,
    name: "Alicia Barillari",
    title: "Associate Account Manager",
    email: "alicia.barillari@weareglow.com",
    phone: "973.580.2441",
  },
  {
    id: 5,
    name: "Ann Ketly",
    title: "Chief Facilitator",
    email: "ann.ketly@weareglow.com",
    phone: "646.270.1782",
  },
  {
    id: 6,
    name: "Annette Lee",
    title: "Finance & Operations Associate",
    email: "annette.lee@weareglow.com",
    phone: "703.541.8315",
  },
  {
    id: 7,
    name: "Austin Arnold",
    title: "Associate Social Media Manager",
    email: "austin.arnold@weareglow.com",
    phone: "503.896.7836",
  },
  {
    id: 8,
    name: "Ben Marko",
    title: "Social Media Intern",
    email: "benjamin.marko@weareglow.com",
    phone: "720.499.9693",
  },
  {
    id: 9,
    name: "Brad Walter",
    title: "Senior Motion Designer",
    email: "brad.walter@weareglow.com",
    phone: "614.378.1924",
  },
  {
    id: 10,
    name: "Cayley Stonehouse",
    title: "Associate Social Media Manager",
    email: "cayley.stonehouse@weareglow.com",
    phone: "203.451.5911",
  },
  {
    id: 11,
    name: "Christopher Rutherford",
    title: "Senior Motion Designer",
    email: "christopher.rutherford@weareglow.com",
    phone: "818.912.1503",
  },
  {
    id: 12,
    name: "Claire Dunderman",
    title: "Project Manager",
    email: "claire.dunderman@weareglow.com",
    phone: "630.287.0519",
  },
  {
    id: 13,
    name: "Clara Lee",
    title: "Creative Director",
    email: "clara.lee@weareglow.com",
    phone: "626.665.2932",
  },
  {
    id: 14,
    name: "Danica Barnett",
    title: "Social Media Manager",
    email: "danica.barnett@weareglow.com",
    phone: "210.744.6536",
  },
  {
    id: 15,
    name: "David Castro-Jimenez",
    title: "Social Media Manager",
    email: "david.castro-jimenez@weareglow.com",
    phone: "310.909.6133",
  },
  {
    id: 16,
    name: "Deb Grant",
    title: "Creative Director",
    email: "deb.grant@weareglow.com",
    phone: "617.821.4464",
  },
  {
    id: 17,
    name: "Dewen Yang",
    title: "Senior Designer",
    email: "dewen.yang@weareglow.com",
    phone: "718.755.7052",
  },
  {
    id: 18,
    name: "Dillon Field",
    title: "Senior Social Media Manager",
    email: "dillon.field@weareglow.com",
    phone: "405.612.3490",
  },
  {
    id: 19,
    name: "Ellie Lloyd",
    title: "Executive Creative Director ",
    email: "ellie.lloyd@weareglow.com",
    phone: "310.740.7559",
  },
  {
    id: 20,
    name: "Em Stone",
    title: "Senior Production Designer",
    email: "em.stone@weareglow.com",
    phone: "917.715.0703",
  },
  {
    id: 21,
    name: "Emily Sireno",
    title: "Creative Director",
    email: "emily.sireno@weareglow.com",
    phone: "973.903.6008",
  },
  {
    id: 22,
    name: "Gabbi Solovay",
    title: "Social Media Manager",
    email: "gabbi.solovay@weareglow.com",
    phone: "954.512.7973",
  },
  {
    id: 23,
    name: "Giac Migliori",
    title: "Senior Manager, Business Operations",
    email: "giac.migliori@weareglow.com",
    phone: "646.726.2936",
  },
  {
    id: 24,
    name: "Holly Roe",
    title: "Associate Creative Director",
    email: "holly.roe@weareglow.com",
    phone: "618.384.9744",
  },
  {
    id: 25,
    name: "Howie Kleinberg",
    title: "President",
    email: "howie.kleinberg@weareglow.com",
    phone: "516.526.9381",
  },
  {
    id: 26,
    name: "Jason Sinclair",
    title: "Head of Strategy",
    email: "jason.sinclair@weareglow.com",
    phone: "718.913.7786",
  },
  {
    id: 27,
    name: "Jenina Estella",
    title: "Director, Digital Strategy & Campaign Development",
    email: "jenina.estella@weareglow.com",
    phone: "917.699.1379",
  },
  {
    id: 28,
    name: "Jenith Damasco",
    title: "VP, Strategy",
    email: "jenith.damasco@weareglow.com",
    phone: "215.510.0945",
  },
  {
    id: 29,
    name: "Jesse Cantu",
    title: "Senior Art Director",
    email: "jesse.cantu@weareglow.com",
    phone: "562.756.6450",
  },
  {
    id: 30,
    name: "Kat McDonald",
    title: "Art Director",
    email: "kat.mcdonald@weareglow.com",
    phone: "978.944.9919",
  },
  {
    id: 31,
    name: "Kate Moore",
    title: "Senior Integrated Producer",
    email: "kate.moore@weareglow.com",
    phone: "631.235.5245",
  },
  {
    id: 32,
    name: "Kevin Kinder",
    title: "Associate Director, Digital & Social Strategy ",
    email: "kevin.kinder@weareglow.com",
    phone: "323.673.0023",
  },
  {
    id: 33,
    name: "Kevin Nelson",
    title: "Account Manager",
    email: "kevin.nelson@weareglow.com",
    phone: "360.367.1832",
  },
  {
    id: 34,
    name: "Kris Crews",
    title: "Project Manager",
    email: "kris.crews@weareglow.com",
    phone: "614.563.6535",
  },
  {
    id: 35,
    name: "Layla Abdul-Jabbar",
    title: "Senior Designer",
    email: "layla.abdul-jabbar@weareglow.com",
    phone: "586.382.0056",
  },
  {
    id: 36,
    name: "Madi Quisenberry",
    title: "Senior Social Media Manager",
    email: "madi.quisenberry@weareglow.com",
    phone: "310.955.7835",
  },
  {
    id: 37,
    name: "Makenzie Boettcher",
    title: "Senior Integrated Producer",
    email: "makenzie.boettcher@weareglow.com",
    phone: "262.573.0748",
  },
  {
    id: 38,
    name: "Marie Takam",
    title: "Manager, Project Management",
    email: "marie.takam@weareglow.com",
    phone: "240.645.2355",
  },
  {
    id: 39,
    name: "Marina Murad",
    title: "Senior Art Director",
    email: "marina.murad@weareglow.com",
    phone: "310.694.1801",
  },
  {
    id: 40,
    name: "Matt Will",
    title: "Creative Developer",
    email: "matt.will@weareglow.com",
    phone: "636.236.9877",
  },
  {
    id: 41,
    name: "Melanie Jacobs-Romero",
    title: "Project Manager",
    email: "melanie.jacobs-romero@weareglow.com",
    phone: "510.685.0582",
  },
  {
    id: 42,
    name: "Mikaela Heyboer",
    title: "Designer",
    email: "mikaela.heyboer@weareglow.com",
    phone: "201.220.5038",
  },
  {
    id: 43,
    name: "Mike Molnar",
    title: "Managing Partner",
    email: "mike.molnar@weareglow.com",
    phone: "917.496.8149",
  },
  {
    id: 44,
    name: "Nathan Lewis",
    title: "Senior Art Director",
    email: "nathan.lewis@weareglow.com",
    phone: "615.974.0354",
  },
  {
    id: 45,
    name: "Nicole Florit",
    title: "Chief Financial Officer ",
    email: "nicole.florit@weareglow.com",
    phone: "920.242.3432",
  },
  {
    id: 46,
    name: "Nicole LaBarre",
    title: "Social Media Intern",
    email: "nicole.labarre@weareglow.com",
    phone: "404.983.3766",
  },
  {
    id: 47,
    name: "Paige Ehlers",
    title: "Senior Designer",
    email: "paige.ehlers@weareglow.com",
    phone: "336.692.5646",
  },
  {
    id: 48,
    name: "Patrick Mullaney",
    title: "VP, Client Services",
    email: "patrick.mullaney@weareglow.com",
    phone: "610.529.7784",
  },
  {
    id: 49,
    name: "Pete Levin",
    title: "Co-Founder & Chief Executive Officer",
    email: "pete.levin@weareglow.com",
    phone: "917.257.2323",
  },
  {
    id: 50,
    name: "Peter Kondratowicz",
    title: "Senior Production Designer",
    email: "pk.kondratowicz@weareglow.com",
    phone: "201.953.1222",
  },
  {
    id: 51,
    name: "Sadie Solomon",
    title: "Project Manager",
    email: "sadie.solomon@weareglow.com",
    phone: "917.239.4893",
  },
  {
    id: 52,
    name: "Sarah Pine",
    title: "Director, Account Services",
    email: "sarah.pine@weareglow.com",
    phone: "201.953.9800",
  },
  {
    id: 53,
    name: "Sarah Powley",
    title: "Senior Social Media Manager",
    email: "sarah.powley@weareglow.com",
    phone: "908.892.2057",
  },
  {
    id: 54,
    name: "Sean Lynam",
    title: "Director, Marketing",
    email: "sean.lynam@weareglow.com",
    phone: "703.618.6326",
  },
  {
    id: 55,
    name: "Shannon Cash",
    title: "Associate Director, Account Services",
    email: "shannon.cash@weareglow.com",
    phone: "248.686.4203",
  },
  {
    id: 56,
    name: "Taylor Panconi",
    title: "Senior Social Media Manager",
    email: "taylor.panconi@weareglow.com",
    phone: "609.235.5290",
  },
  {
    id: 57,
    name: "Ted Kacandes",
    title: "Co-Founder & Chief Creative Officer",
    email: "ted.kacandes@weareglow.com",
    phone: "347.538.8045",
  },
];
