export const employees = [
  {
    id: 0,
    name: "Adrien Hobbs",
    title: "Developer",
    email: "adrien.hobbs@weareglow.com",
    phone: "212-206-7370",
  },
  {
    id: 1,
    name: "Alan Pierson",
    title: "Senior Integrated Producer",
    email: "alan.pierson@weareglow.com",
    phone: "212-206-7371",
  },
  {
    id: 2,
    name: "Alex Chang",
    title: "Client Operations & Project Manager",
    email: "alex.chang@weareglow.com",
    phone: "212-206-7372",
  },
  {
    id: 3,
    name: "Alex Husband",
    title: "Associate Creative Director",
    email: "alex.husband@weareglow.com",
    phone: "212-206-7373",
  },
  {
    id: 4,
    name: "Alicia Barillari",
    title: "Associate Account Manager",
    email: "alicia.barillari@weareglow.com",
    phone: "212-206-7374",
  },
  {
    id: 5,
    name: "Ann Ketly",
    title: "Chief Facilitator",
    email: "ann.ketly@weareglow.com",
    phone: "212-206-7375",
  },
  {
    id: 6,
    name: "Annette Lee",
    title: "Finance & Operations Associate",
    email: "annette.lee@weareglow.com",
    phone: "212-206-7376",
  },
  {
    id: 7,
    name: "Austin Arnold",
    title: "Associate Social Media Manager",
    email: "austin.arnold@weareglow.com",
    phone: "212-206-7377",
  },
  {
    id: 8,
    name: "Ben Marko",
    title: "Social Media Intern",
    email: "benjamin.marko@weareglow.com",
    phone: "212-206-7378",
  },
  {
    id: 9,
    name: "Brad Walter",
    title: "Senior Motion Designer",
    email: "brad.walter@weareglow.com",
    phone: "212-206-7379",
  },
  {
    id: 10,
    name: "Carlota Crespo",
    title: "Social Media Intern",
    email: "carlota.crespo@weareglow.com",
    phone: "212-206-7380",
  },
  {
    id: 11,
    name: "Cayley Stonehouse",
    title: "Associate Social Media Manager",
    email: "cayley.stonehouse@weareglow.com",
    phone: "212-206-7381",
  },
  {
    id: 12,
    name: "Christopher Rutherford",
    title: "Senior Motion Designer",
    email: "christopher.rutherford@weareglow.com",
    phone: "212-206-7383",
  },
  {
    id: 13,
    name: "Claire Dunderman",
    title: "Project Manager",
    email: "claire.dunderman@weareglow.com",
    phone: "212-206-7384",
  },
  {
    id: 14,
    name: "Clara Lee",
    title: "Creative Director",
    email: "clara.lee@weareglow.com",
    phone: "212-206-7385",
  },
  {
    id: 15,
    name: "Danica Barnett",
    title: "Social Media Manager",
    email: "danica.barnett@weareglow.com",
    phone: "212-206-7386",
  },
  {
    id: 16,
    name: "David Castro-Jimenez",
    title: "Social Media Manager",
    email: "david.castro-jimenez@weareglow.com",
    phone: "212-206-7387",
  },
  {
    id: 17,
    name: "Deb Grant",
    title: "Creative Director",
    email: "deb.grant@weareglow.com",
    phone: "212-206-7388",
  },
  {
    id: 18,
    name: "Dewen Yang",
    title: "Senior Designer",
    email: "dewen.yang@weareglow.com",
    phone: "212-206-7389",
  },
  {
    id: 19,
    name: "Dillon Field",
    title: "Senior Social Media Manager",
    email: "dillon.field@weareglow.com",
    phone: "212-206-7390",
  },
  {
    id: 20,
    name: "Ellie Lloyd",
    title: "Executive Creative Director ",
    email: "ellie.lloyd@weareglow.com",
    phone: "212-206-7391",
  },
  {
    id: 21,
    name: "Em Stone",
    title: "Senior Production Designer",
    email: "em.stone@weareglow.com",
    phone: "212-206-7392",
  },
  {
    id: 22,
    name: "Emily Sireno",
    title: "Creative Director",
    email: "emily.sireno@weareglow.com",
    phone: "212-206-7393",
  },
  {
    id: 23,
    name: "Gabbi Solovay",
    title: "Social Media Manager",
    email: "gabbi.solovay@weareglow.com",
    phone: "212-206-7394",
  },
  {
    id: 24,
    name: "Giac Migliori",
    title: "Senior Manager, Business Operations",
    email: "giac.migliori@weareglow.com",
    phone: "212-206-7395",
  },
  {
    id: 25,
    name: "Holly Roe",
    title: "Associate Creative Director",
    email: "holly.roe@weareglow.com",
    phone: "212-206-7396",
  },
  {
    id: 26,
    name: "Howie Kleinberg",
    title: "President",
    email: "howie.kleinberg@weareglow.com",
    phone: "212-206-7397",
  },
  {
    id: 27,
    name: "Jason Sinclair",
    title: "Head of Strategy",
    email: "jason.sinclair@weareglow.com",
    phone: "212-206-7399",
  },
  {
    id: 28,
    name: "Jenina Estella",
    title: "Director, Digital Strategy & Campaign Development",
    email: "jenina.estella@weareglow.com",
    phone: "212-206-7400",
  },
  {
    id: 29,
    name: "Jenith Damasco",
    title: "VP, Strategy",
    email: "jenith.damasco@weareglow.com",
    phone: "212-206-7401",
  },
  {
    id: 30,
    name: "Jesse Cantu",
    title: "Senior Art Director",
    email: "jesse.cantu@weareglow.com",
    phone: "212-206-7402",
  },
  {
    id: 31,
    name: "Kat McDonald",
    title: "Art Director",
    email: "kat.mcdonald@weareglow.com",
    phone: "212-206-7403",
  },
  {
    id: 32,
    name: "Kate Moore",
    title: "Senior Integrated Producer",
    email: "kate.moore@weareglow.com",
    phone: "212-206-7404",
  },
  {
    id: 33,
    name: "Kevin Kinder",
    title: "Associate Director, Digital & Social Strategy ",
    email: "kevin.kinder@weareglow.com",
    phone: "212-206-7405",
  },
  {
    id: 34,
    name: "Kevin Nelson",
    title: "Account Manager",
    email: "kevin.nelson@weareglow.com",
    phone: "212-206-7406",
  },
  {
    id: 35,
    name: "Kris Crews",
    title: "Project Manager",
    email: "kris.crews@weareglow.com",
    phone: "212-206-7407",
  },
  {
    id: 36,
    name: "Layla Abdul-Jabbar",
    title: "Senior Designer",
    email: "layla.abdul-jabbar@weareglow.com",
    phone: "212-206-7408",
  },
  {
    id: 37,
    name: "Madi Quisenberry",
    title: "Senior Social Media Manager",
    email: "madi.quisenberry@weareglow.com",
    phone: "212-206-7409",
  },
  {
    id: 38,
    name: "Makenzie Boettcher",
    title: "Senior Integrated Producer",
    email: "makenzie.boettcher@weareglow.com",
    phone: "212-206-7410",
  },
  {
    id: 39,
    name: "Marie Takam",
    title: "Manager, Project Management",
    email: "marie.takam@weareglow.com",
    phone: "212-206-7411",
  },
  {
    id: 40,
    name: "Marina Murad",
    title: "Senior Art Director",
    email: "marina.murad@weareglow.com",
    phone: "212-206-7412",
  },
  {
    id: 41,
    name: "Matt Will",
    title: "Creative Developer",
    email: "matt.will@weareglow.com",
    phone: "212-206-7413",
  },
  {
    id: 42,
    name: "Melanie Jacobs-Romero",
    title: "Project Manager",
    email: "melanie.jacobs-romero@weareglow.com",
    phone: "212-206-7414",
  },
  {
    id: 43,
    name: "Mikaela Heyboer",
    title: "Designer",
    email: "mikaela.heyboer@weareglow.com",
    phone: "212-206-7415",
  },
  {
    id: 44,
    name: "Mike Molnar",
    title: "Managing Partner",
    email: "mike.molnar@weareglow.com",
    phone: "212-206-7416",
  },
  {
    id: 45,
    name: "Nathan Lewis",
    title: "Senior Art Director",
    email: "nathan.lewis@weareglow.com",
    phone: "212-206-7417",
  },
  {
    id: 46,
    name: "Nicole Florit",
    title: "Chief Financial Officer ",
    email: "nicole.florit@weareglow.com",
    phone: "212-206-7418",
  },
  {
    id: 47,
    name: "Nicole LaBarre",
    title: "Social Media Intern",
    email: "nicole.labarre@weareglow.com",
    phone: "212-206-7419",
  },
  {
    id: 48,
    name: "Paige Ehlers",
    title: "Senior Designer",
    email: "paige.ehlers@weareglow.com",
    phone: "212-206-7420",
  },
  {
    id: 49,
    name: "Patrick Mullaney",
    title: "VP, Client Services",
    email: "patrick.mullaney@weareglow.com",
    phone: "212-206-7421",
  },
  {
    id: 50,
    name: "Pete Levin",
    title: "Co-Founder & Chief Executive Officer",
    email: "pete.levin@weareglow.com",
    phone: "212-206-7422",
  },
  {
    id: 51,
    name: "PK Kondratowicz",
    title: "Senior Production Designer",
    email: "pk.kondratowicz@weareglow.com",
    phone: "212-206-7423",
  },
  {
    id: 52,
    name: "Sadie Solomon",
    title: "Project Manager",
    email: "sadie.solomon@weareglow.com",
    phone: "212-206-7425",
  },
  {
    id: 53,
    name: "Sarah Pine",
    title: "Director, Account Services",
    email: "sarah.pine@weareglow.com",
    phone: "212-206-7426",
  },
  {
    id: 54,
    name: "Sarah Powley",
    title: "Senior Social Media Manager",
    email: "sarah.powley@weareglow.com",
    phone: "212-206-7427",
  },
  {
    id: 55,
    name: "Sean Lynam",
    title: "Director, Marketing",
    email: "sean.lynam@weareglow.com",
    phone: "212-206-7428",
  },
  {
    id: 56,
    name: "Shannon Cash",
    title: "Associate Director, Account Services",
    email: "shannon.cash@weareglow.com",
    phone: "212-206-7429",
  },
  {
    id: 57,
    name: "Taylor Panconi",
    title: "Senior Social Media Manager",
    email: "taylor.panconi@weareglow.com",
    phone: "212-206-7430",
  },
  {
    id: 58,
    name: "Ted Kacandes",
    title: "Co-Founder & Chief Creative Officer",
    email: "ted.kacandes@weareglow.com",
    phone: "212-206-7431",
  },
];
